version: "3.0"
services:
  default:
    container_name: default
    build: ./src/default
    volumes:
      - "./src/default:/src"
  crypto:
    container_name: crypto
    build: ./src/crypto
    volumes:
      - "./src/crypto:/src"
  static:
    container_name: static
    image: nginx:1.19.6
    ports:
      - "8080:8080"
    volumes:
      - "./default.conf:/etc/nginx/conf.d/default.conf"
